export enum ErrorStatus {
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  SERVICE_UNAVAILABLE = 503,
  CLIENT_ERROR = "CLIENT_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  EMPTY_DATA = "EMPTY_DATA",
}